#include "HsFFI.h"
#ifdef __cplusplus
extern "C" {
#endif
extern HsInt hs_get_local_zone(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_get_int_local_zone(HsStablePtr a1, HsPtr a2);
extern HsInt hs_get_some_local_zone(HsStablePtr a1, HsPtr a2, HsInt a3, HsInt a4);
extern HsInt hs_get_some2_local_zone(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_all_local_zone(HsStablePtr a1, HsPtr a2);
extern HsInt hs_get_zone_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_zone_id(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_zone_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_zone_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_zone_id(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_num_data_by_resc(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_num_data_by_resc(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_num_data_by_resc(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_num_data_by_resc(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_num_data_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_num_data_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_num_data_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_num_data_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_token_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_token_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_token_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_token_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_token_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_token_name_by_namespace_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_some_token_name_by_namespace_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_token_name_by_namespace_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_token_name_by_namespace_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_resc_group_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_resc_group_id(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_resc_group_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_resc_group_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_resc_group_id(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_resc_parent_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_resc_parent_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_resc_parent_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_resc_parent_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_resc_parent_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_resc_type_name_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_resc_type_name_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_resc_type_name_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_resc_type_name_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_resc_type_name_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_coll_child_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_coll_child_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_coll_child_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_coll_child_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_coll_child_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_password_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_password_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_password_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_password_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_password_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_user_password_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_some_user_password_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_user_password_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_user_password_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_user_password_by_user_and_expiry_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_some_user_password_by_user_and_expiry_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6, HsInt a7);
extern HsInt hs_get_some2_user_password_by_user_and_expiry_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_all_user_password_by_user_and_expiry_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_get_coll_id_if_own_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_int_coll_id_if_own_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_get_some_coll_id_if_own_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6, HsInt a7);
extern HsInt hs_get_some2_coll_id_if_own_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_all_coll_id_if_own_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_get_coll_if_modify_object_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_some_coll_if_modify_object_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6, HsInt a7);
extern HsInt hs_get_some2_coll_if_modify_object_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_all_coll_if_modify_object_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_get_coll_if_own_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_some_coll_if_own_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6, HsInt a7);
extern HsInt hs_get_some2_coll_if_own_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_all_coll_if_own_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_get_sub_coll_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_sub_coll_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_sub_coll_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_sub_coll_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_sub_coll_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_resc_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_resc_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_resc_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_resc_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_resc_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_resc_id_by_data_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_resc_id_by_data_id(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_resc_id_by_data_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_resc_id_by_data_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_resc_id_by_data_id(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_resc_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_resc_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_resc_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_resc_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_resc_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_user_id_with_password(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_user_id_with_password(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_user_id_with_password(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_user_id_with_password(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_user_id_with_password(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_meta_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_int_meta_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_get_some_meta_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6, HsInt a7);
extern HsInt hs_get_some2_meta_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_all_meta_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_get_meta_id_by_attribute_and_value(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_meta_id_by_attribute_and_value(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_meta_id_by_attribute_and_value(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_meta_id_by_attribute_and_value(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_meta_id_by_attribute_and_value(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_meta_id_by_attribute_and_obj_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_meta_id_by_attribute_and_obj_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_meta_id_by_attribute_and_obj_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_meta_id_by_attribute_and_obj_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_meta_id_by_attribute_and_obj_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_coll_id_by_data(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_coll_id_by_data(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_coll_id_by_data(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_coll_id_by_data(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_coll_id_by_data(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_coll_id_by_coll(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_coll_id_by_coll(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_coll_id_by_coll(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_coll_id_by_coll(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_coll_id_by_coll(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_coll_id_by_coll_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_coll_id_by_coll_id(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_coll_id_by_coll_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_coll_id_by_coll_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_coll_id_by_coll_id(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_coll_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_coll_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_coll_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_coll_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_coll_id_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_non_group_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_non_group_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_non_group_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_non_group_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_non_group_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_group_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_group_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_group_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_group_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_group_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_user_type_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_user_type_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_user_type_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_user_type_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_user_type_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_password_by_user_zone_and_name_and_diff_expiry_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_int_password_by_user_zone_and_name_and_diff_expiry_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_get_some_password_by_user_zone_and_name_and_diff_expiry_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6, HsInt a7);
extern HsInt hs_get_some2_password_by_user_zone_and_name_and_diff_expiry_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_all_password_by_user_zone_and_name_and_diff_expiry_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_get_data_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_data_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_data_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_data_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_data_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_repl_resc_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_repl_resc_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_repl_resc_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_repl_resc_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_repl_resc_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_repl2(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_some_repl2(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_repl2(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_repl2(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_repl2_by_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_some_repl2_by_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_repl2_by_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_repl2_by_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_max_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_max_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_max_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_max_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_max_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_diff_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_diff_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_diff_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_diff_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_diff_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_resc_parent(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_resc_parent(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_resc_parent(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_resc_parent(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_resc_parent(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_resc_child(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_resc_child(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_resc_child(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_resc_child(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_resc_child(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_resc_def_path(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_resc_def_path(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_resc_def_path(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_resc_def_path(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_resc_def_path(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_zone_type_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_zone_type_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_zone_type_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_zone_type_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_zone_type_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_num_password_by_user_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_num_password_by_user_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_num_password_by_user_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_num_password_by_user_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_data_name_by_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_int_data_name_by_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_get_some_data_name_by_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6, HsInt a7);
extern HsInt hs_get_some2_data_name_by_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_all_data_name_by_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_get_quota_by_user_name_and_resc_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_some_quota_by_user_name_and_resc_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_quota_by_user_name_and_resc_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_quota_by_user_name_and_resc_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_num_data_by_resc_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_int_num_data_by_resc_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_num_data_by_resc_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_num_data_by_resc_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_num_data_by_resc_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_data_by_resc_not_in_child(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_data_by_resc_not_in_child(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_data_by_resc_not_in_child(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_data_by_resc_not_in_child(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_data_by_resc_not_in_child(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_data_by_resc_list(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_data_by_resc_list(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_data_by_resc_list(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_data_by_resc_list(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_data_by_resc_list(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_next_id(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_get_int_next_id(HsStablePtr a1, HsPtr a2);
extern HsInt hs_get_some_next_id(HsStablePtr a1, HsPtr a2, HsInt a3, HsInt a4);
extern HsInt hs_get_some2_next_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4);
extern HsInt hs_get_all_next_id(HsStablePtr a1, HsPtr a2);
extern HsInt hs_get_resc_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_int_resc_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_get_some_resc_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7, HsInt a8);
extern HsInt hs_get_some2_resc_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsInt a8);
extern HsInt hs_get_all_resc_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_get_coll_id_by_coll_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_int_coll_id_by_coll_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_get_some_coll_id_by_coll_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7, HsInt a8);
extern HsInt hs_get_some2_coll_id_by_coll_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsInt a8);
extern HsInt hs_get_all_coll_id_by_coll_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_get_coll_id_by_own(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_int_coll_id_by_own(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_get_some_coll_id_by_own(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6, HsInt a7);
extern HsInt hs_get_some2_coll_id_by_own(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_all_coll_id_by_own(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_get_coll_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_int_coll_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_get_some_coll_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7, HsInt a8);
extern HsInt hs_get_some2_coll_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsInt a8);
extern HsInt hs_get_all_coll_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_get_coll_id_and_inheritance_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_some_coll_id_and_inheritance_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7, HsInt a8);
extern HsInt hs_get_some2_coll_id_and_inheritance_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsInt a8);
extern HsInt hs_get_all_coll_id_and_inheritance_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_get_data_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsInt a8);
extern HsInt hs_get_int_data_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7);
extern HsInt hs_get_some_data_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsInt a8, HsInt a9);
extern HsInt hs_get_some2_data_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsInt a9);
extern HsInt hs_get_all_data_id_by_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7);
extern HsInt hs_get_data_id_by_own(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_int_data_id_by_own(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_get_some_data_id_by_own(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7, HsInt a8);
extern HsInt hs_get_some2_data_id_by_own(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsInt a8);
extern HsInt hs_get_all_data_id_by_own(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_get_group_id_by_user(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_group_id_by_user(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_group_id_by_user(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_group_id_by_user(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_group_id_by_user(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_data_id_by_data_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_int_data_id_by_data_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_get_some_data_id_by_data_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7, HsInt a8);
extern HsInt hs_get_some2_data_id_by_data_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsInt a8);
extern HsInt hs_get_all_data_id_by_data_id_and_access(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_get_group_admin_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_int_group_admin_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_some_group_admin_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5, HsInt a6);
extern HsInt hs_get_some2_group_admin_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6);
extern HsInt hs_get_all_group_admin_user_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_get_group_member_count(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_some_group_member_count(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsInt a5);
extern HsInt hs_get_some2_group_member_count(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsInt a5);
extern HsInt hs_get_all_group_member_count(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_get_access_permission_use_wildcard(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_int_access_permission_use_wildcard(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_get_some_access_permission_use_wildcard(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7, HsInt a8);
extern HsInt hs_get_some2_access_permission_use_wildcard(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsInt a8);
extern HsInt hs_get_all_access_permission_use_wildcard(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_get_num_access_permission_use_wildcard(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7);
extern HsInt hs_get_int_num_access_permission_use_wildcard(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_get_some_num_access_permission_use_wildcard(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsInt a7, HsInt a8);
extern HsInt hs_get_some2_num_access_permission_use_wildcard(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsInt a8);
extern HsInt hs_get_all_num_access_permission_use_wildcard(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_create_user(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7);
extern HsInt hs_update_user(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7);
extern HsInt hs_array_create_user(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_access_by_access_type_token(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_update_access_by_access_type_token(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_array_create_access_by_access_type_token(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_metamap_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_update_metamap_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_array_create_metamap_by_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_metamap(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_metamap(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_metamap(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_meta_map_by_obj_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_meta_map_by_obj_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_meta_map_by_obj_id(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_meta_value_and_units_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_meta_value_and_units_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_meta_value_and_units_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_resc_parent_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_resc_parent_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_resc_parent_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_user_password_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7);
extern HsInt hs_update_user_password_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7);
extern HsInt hs_array_create_user_password_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_user_password_by_user(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_user_password_by_user(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_user_password_by_user(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_data_access_by_user_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_update_data_access_by_user_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_array_create_data_access_by_user_recursive(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_coll_access_by_user_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_update_coll_access_by_user_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_array_create_coll_access_by_user_recursive(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_user_group(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_user_group(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_user_group(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_meta(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7);
extern HsInt hs_update_meta(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7);
extern HsInt hs_array_create_meta(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_coll_inheritance_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_coll_inheritance_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_coll_inheritance_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_coll_modify_ts(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_update_coll_modify_ts(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_array_create_coll_modify_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_coll_name_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_coll_name_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_coll_name_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_coll_inheritance_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_coll_inheritance_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_coll_inheritance_by_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_user_password(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_update_user_password(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_array_create_user_password(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_password_expiry_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_password_expiry_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_password_expiry_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_repl2(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsPtr a9, HsPtr a10, HsPtr a11, HsPtr a12, HsPtr a13, HsPtr a14, HsPtr a15, HsPtr a16, HsPtr a17, HsPtr a18, HsPtr a19, HsPtr a20);
extern HsInt hs_update_repl2(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsPtr a9, HsPtr a10, HsPtr a11, HsPtr a12, HsPtr a13, HsPtr a14, HsPtr a15, HsPtr a16, HsPtr a17, HsPtr a18, HsPtr a19, HsPtr a20);
extern HsInt hs_array_create_repl2(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_repl2_by_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsPtr a9, HsPtr a10, HsPtr a11, HsPtr a12, HsPtr a13, HsPtr a14, HsPtr a15, HsPtr a16, HsPtr a17, HsPtr a18, HsPtr a19, HsPtr a20);
extern HsInt hs_update_repl2_by_repl_num(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsPtr a9, HsPtr a10, HsPtr a11, HsPtr a12, HsPtr a13, HsPtr a14, HsPtr a15, HsPtr a16, HsPtr a17, HsPtr a18, HsPtr a19, HsPtr a20);
extern HsInt hs_array_create_repl2_by_repl_num(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_repl(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsPtr a9, HsPtr a10, HsPtr a11, HsPtr a12, HsPtr a13, HsPtr a14, HsPtr a15, HsPtr a16, HsPtr a17, HsPtr a18, HsPtr a19, HsPtr a20);
extern HsInt hs_update_repl(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsPtr a9, HsPtr a10, HsPtr a11, HsPtr a12, HsPtr a13, HsPtr a14, HsPtr a15, HsPtr a16, HsPtr a17, HsPtr a18, HsPtr a19, HsPtr a20);
extern HsInt hs_array_create_repl(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_access_inherit_coll(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_access_inherit_coll(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_access_inherit_coll(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7);
extern HsInt hs_update_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7);
extern HsInt hs_array_create_access_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_access_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8);
extern HsInt hs_update_access_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8);
extern HsInt hs_array_create_access_recursive(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_resc(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsPtr a9, HsPtr a10, HsPtr a11, HsPtr a12, HsPtr a13);
extern HsInt hs_update_resc(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsPtr a9, HsPtr a10, HsPtr a11, HsPtr a12, HsPtr a13);
extern HsInt hs_array_create_resc(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_coll(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsPtr a9, HsPtr a10, HsPtr a11);
extern HsInt hs_update_coll(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsPtr a9, HsPtr a10, HsPtr a11);
extern HsInt hs_array_create_coll(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_zone(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8);
extern HsInt hs_update_zone(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8);
extern HsInt hs_array_create_zone(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_zone_comment_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_zone_comment_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_zone_comment_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_resc_comment_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_resc_comment_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_resc_comment_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_resc_info_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_resc_info_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_resc_info_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_zone_conn_string_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_zone_conn_string_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_zone_conn_string_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_zone_name_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_zone_name_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_zone_name_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_coll_owner_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_coll_owner_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_coll_owner_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_data_owner_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_data_owner_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_data_owner_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_resc_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_resc_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_resc_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_resc_free_space_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_resc_free_space_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_resc_free_space_by_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_resc_free_space_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_resc_free_space_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_resc_free_space_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_resc_net_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_resc_net_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_resc_net_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_resc_type_name_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_resc_type_name_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_resc_type_name_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_resc_def_path(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_update_resc_def_path(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_array_create_resc_def_path(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_resc_def_path_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_resc_def_path_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_resc_def_path_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_resc_status_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_resc_status_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_resc_status_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_resc_name_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_resc_name_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_resc_name_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_server_load_resc_name_by_resc_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_update_server_load_resc_name_by_resc_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_array_create_server_load_resc_name_by_resc_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_server_load_digest_resc_name_by_resc_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_update_server_load_digest_resc_name_by_resc_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_array_create_server_load_digest_resc_name_by_resc_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_resc_context_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_resc_context_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_resc_context_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_rule_owner_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_rule_owner_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_rule_owner_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_user_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_user_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_user_zone_by_zone_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_zone_name_by_zone_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_zone_name_by_zone_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_zone_name_by_zone_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_data_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_update_data_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_array_create_data_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_coll_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_coll_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_coll_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_data_coll_id_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_data_coll_id_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_data_coll_id_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_token(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsPtr a9, HsPtr a10);
extern HsInt hs_update_token(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsPtr a9, HsPtr a10);
extern HsInt hs_array_create_token(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_server_load(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsPtr a9, HsPtr a10, HsPtr a11);
extern HsInt hs_update_server_load(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6, HsPtr a7, HsPtr a8, HsPtr a9, HsPtr a10, HsPtr a11);
extern HsInt hs_array_create_server_load(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_server_load_digest(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_server_load_digest(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_server_load_digest(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_quota_usage_by_modify_ts(HsStablePtr a1, HsPtr a2);
extern HsInt hs_update_quota_usage_by_modify_ts(HsStablePtr a1, HsPtr a2);
extern HsInt hs_array_create_quota_usage_by_modify_ts(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_quota_usage(HsStablePtr a1, HsPtr a2);
extern HsInt hs_update_quota_usage(HsStablePtr a1, HsPtr a2);
extern HsInt hs_array_create_quota_usage(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_quota(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_quota(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_quota(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_user_type_by_name_and_user_type_token(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_user_type_by_name_and_user_type_token(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_user_type_by_name_and_user_type_token(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_user_zone_name_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_user_zone_name_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_user_zone_name_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_user_auth_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_user_auth_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_user_auth_by_user_zone_and_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_user_info_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_user_info_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_user_info_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_user_comment_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_update_user_comment_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_array_create_user_comment_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_data_path_by_user_zone_and_name_and_resc_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_update_data_path_by_user_zone_and_name_and_resc_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsPtr a6);
extern HsInt hs_array_create_data_path_by_user_zone_and_name_and_resc_name(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_data_path(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_data_path(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_data_path(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_coll_name_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_update_coll_name_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_array_create_coll_name_recursive(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_data_resc_hier_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_data_resc_hier_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_data_resc_hier_recursive(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_data_resc_hier(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_update_data_resc_hier(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_array_create_data_resc_hier(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_create_coll_parent_coll_name_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_update_coll_parent_coll_name_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_array_create_coll_parent_coll_name_recursive(HsStablePtr a1, HsPtr a2, HsInt a3);
extern HsInt hs_delete_metamap_by_obj_id(HsStablePtr a1, HsPtr a2);
extern HsInt hs_delete_access_by_obj_id_and_user(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_delete_avus(HsStablePtr a1);
extern HsInt hs_delete_coll_by_name(HsStablePtr a1, HsPtr a2);
extern HsInt hs_delete_access_by_obj_id(HsStablePtr a1, HsPtr a2);
extern HsInt hs_delete_access_by_coll_name(HsStablePtr a1, HsPtr a2);
extern HsInt hs_delete_user_password_by_user_zone_and_name_and_create_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_delete_user_password_by_user_zone_and_name_and_expiry_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_delete_user_password_by_user(HsStablePtr a1, HsPtr a2);
extern HsInt hs_delete_user_password_by_expiry_ts_and_modify_ts(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_delete_data_access_by_user_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_delete_coll_access_by_user_recursive(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_delete_user_password_by_password(HsStablePtr a1, HsPtr a2);
extern HsInt hs_delete_user_password_by_expiry_ts_and_create_ts(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_delete_user_group(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_delete_user_auth(HsStablePtr a1, HsPtr a2);
extern HsInt hs_delete_resc_by_name(HsStablePtr a1, HsPtr a2);
extern HsInt hs_delete_metamap_by_attribute_and_obj_id(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_delete_metamap_allow_null_units_use_wildcards(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_delete_metamap_allow_null_units(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_delete_metamap_use_wildcards(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_delete_metamap_by_avu_and_obj_id(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5);
extern HsInt hs_delete_user_by_zone_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_delete_repl_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_delete_data_by_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_delete_rule_exec(HsStablePtr a1, HsPtr a2);
extern HsInt hs_delete_zone_by_name(HsStablePtr a1, HsPtr a2);
extern HsInt hs_delete_token_by_namespace_and_name(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_delete_server_load_by_create_ts(HsStablePtr a1, HsPtr a2);
extern HsInt hs_delete_server_load_digest_by_create_ts(HsStablePtr a1, HsPtr a2);
extern HsInt hs_delete_quota_usage_by_modify_ts(HsStablePtr a1, HsPtr a2);
extern HsInt hs_delete_quota_by_user_id_and_resc_id(HsStablePtr a1, HsPtr a2, HsPtr a3);
extern HsInt hs_delete_user_auth_by_user_name(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4);
extern HsInt hs_connect(HsPtr a1);
extern HsInt hs_disconnect(HsStablePtr a1);
extern HsInt hs_commit(HsStablePtr a1);
extern HsInt hs_rollback(HsStablePtr a1);
extern HsInt hs_modify_data(HsStablePtr a1, HsPtr a2, HsPtr a3, HsPtr a4, HsPtr a5, HsInt a6, HsInt a7);
extern HsInt hs_modify_coll(HsStablePtr a1, HsPtr a2, HsPtr a3, HsInt a4, HsPtr a5);
#ifdef __cplusplus
}
#endif

